### ISSUE TITLE
Track unparsable dates

### ISSUE THREAD

**Issue by shirey** [dbmi-pitt/path-redcap-to-cdm#9]
When parsing dates to store in the pro_response_date field, if there is data coming from RedCap, but it can't be parsed store a "unparsable date value" code in the path_code field for this record.

**Comment by cborromeo** [comment]
I ran the code.  This query returns 8 records:

select * from cdm_41_etl.PRO_CM
where path_code like '%UNPARSE%'

The PATH_CODE field contains values like: PRO:1002_f26_q8:UNPARSEABLE_DATE

**Comment by nkc7** [comment]
@cborromeo We'll have to ignore these then...

**Comment by cborromeo** [comment]
@shirey @nkc7 I just ran my code that skips these records.  Here are the results:

IPF: 2184 forms skipped out of 9289 (23%)
AFib: 6728 forms skipped out of 100887 (6%)
Weight: 27729 forms skipped out of 128802 (21%)

**Comment by nkc7** [comment]
Wow… seems like a lot – any idea if they are just a few questions?

Nickie Cappella

Senior Project Manager | Department of Biomedical Informatics  | Tel: 412-624-5459 | Email:  nkc7@pitt.edu<mailto:nkc7@pitt.edu>

**Comment by cborromeo** [comment]
@nkc7 these numbers represent forms where the timestamp field is either blank or set to '[not completed]'.  I have an Excel file representing the AFib data exported from REDCap.  I can send you a copy of the file.  It is fairly easy to find the '[not completed]' by searching the file.  However, the empty fields are harder to find since many of the fields in the file are empty.

**Comment by nkc7** [comment]
@cborromeo ok -i'd like to see but not urgent

**Comment by shirey** [comment]
@nkc7 Please review
